### ISSUE TITLE
Emails font size

### ISSUE THREAD

**Issue by alexanderzky** [jsdevkr/react-multi-email#17]
Hi Thomas!
I can't figure out how to change font size of emails in input. 
Changing fontSize in style of <ReactMultiEmail> only changes the size of placeholder text.

**Comment by thomasJang** [comment]
![image](https://user-images.githubusercontent.com/5884902/54865691-cbc66000-4dac-11e9-93b1-918d1a0be0d1.png)

```css
.react-multi-email [data-tag] {
  font-size: ??px
}
```

You can change fontSize here.
